# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import functions as f


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_index = QtWidgets.QWidget()
        self.tab_index.setObjectName("tab_index")
        self.checkBox_SIFT_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_SIFT_index.setGeometry(QtCore.QRect(20, 10, 85, 21))
        self.checkBox_SIFT_index.setObjectName("checkBox_SIFT_index")
        self.checkBox_ORB_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_ORB_index.setGeometry(QtCore.QRect(140, 10, 85, 21))
        self.checkBox_ORB_index.setObjectName("checkBox_ORB_index")
        self.checkBox_HSV_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HSV_index.setGeometry(QtCore.QRect(470, 10, 101, 21))
        self.checkBox_HSV_index.setObjectName("checkBox_HSV_index")
        self.checkBox_HistC_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HistC_index.setGeometry(QtCore.QRect(270, 10, 121, 21))
        self.checkBox_HistC_index.setObjectName("checkBox_HistC_index")
        self.checkBox_GLCM_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_GLCM_index.setGeometry(QtCore.QRect(650, 10, 81, 21))
        self.checkBox_GLCM_index.setObjectName("checkBox_GLCM_index")
        self.checkBox_LBP_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_LBP_index.setGeometry(QtCore.QRect(800, 10, 61, 21))
        self.checkBox_LBP_index.setObjectName("checkBox_LBP_index")
        self.checkBox_HOG_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HOG_index.setGeometry(QtCore.QRect(930, 10, 71, 21))
        self.checkBox_HOG_index.setObjectName("checkBox_HOG_index")
        self.charger = QtWidgets.QPushButton(self.tab_index)
        self.charger.setGeometry(QtCore.QRect(10, 50, 441, 51))
        self.charger.setObjectName("charger")
        self.quitter = QtWidgets.QPushButton(self.tab_index)
        self.quitter.setGeometry(QtCore.QRect(930, 50, 71, 51))
        self.quitter.setObjectName("quitter")
        self.indexer = QtWidgets.QPushButton(self.tab_index)
        self.indexer.setGeometry(QtCore.QRect(470, 50, 451, 51))
        self.indexer.setObjectName("indexer")
        self.imagelabel = QtWidgets.QLabel(self.tab_index)
        self.imagelabel.setGeometry(QtCore.QRect(10, 110, 261, 231))
        self.imagelabel.setAutoFillBackground(False)
        self.imagelabel.setText("")
        self.imagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imagelabel.setObjectName("imagelabel")
        self.image = QtWidgets.QLabel(self.tab_index)
        self.image.setGeometry(QtCore.QRect(10, 160, 441, 331))
        self.image.setFrameShape(QtWidgets.QFrame.Panel)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.label_3 = QtWidgets.QLabel(self.tab_index)
        self.label_3.setGeometry(QtCore.QRect(470, 120, 531, 31))
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab_index)
        self.label.setGeometry(QtCore.QRect(10, 120, 441, 31))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.tab_index)
        self.progressBar.setGeometry(QtCore.QRect(10, 510, 1011, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tableView = QtWidgets.QTableView(self.tab_index)
        self.tableView.setGeometry(QtCore.QRect(470, 160, 531, 331))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_index, "")
        self.tab_rech = QtWidgets.QWidget()
        self.tab_rech.setObjectName("tab_rech")
        self.label_2 = QtWidgets.QLabel(self.tab_rech)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.checkBox_HistC_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HistC_rech.setGeometry(QtCore.QRect(110, 50, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.checkBox_HistC_rech.setFont(font)
        self.checkBox_HistC_rech.setObjectName("checkBox_HistC_rech")
        self.checkBox_HSV_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HSV_rech.setGeometry(QtCore.QRect(190, 50, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HSV_rech.setFont(font)
        self.checkBox_HSV_rech.setObjectName("checkBox_HSV_rech")
        self.checkBox_SIFT_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_SIFT_rech.setGeometry(QtCore.QRect(110, 80, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_SIFT_rech.setFont(font)
        self.checkBox_SIFT_rech.setObjectName("checkBox_SIFT_rech")
        self.checkBox_ORB_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_ORB_rech.setGeometry(QtCore.QRect(190, 80, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ORB_rech.setFont(font)
        self.checkBox_ORB_rech.setObjectName("checkBox_ORB_rech")
        self.checkBox_GLCM_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_GLCM_rech.setGeometry(QtCore.QRect(190, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_GLCM_rech.setFont(font)
        self.checkBox_GLCM_rech.setObjectName("checkBox_GLCM_rech")
        self.checkBox_LBP_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_LBP_rech.setGeometry(QtCore.QRect(110, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_LBP_rech.setFont(font)
        self.checkBox_LBP_rech.setObjectName("checkBox_LBP_rech")
        self.checkBox_HOG_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HOG_rech.setGeometry(QtCore.QRect(290, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HOG_rech.setFont(font)
        self.checkBox_HOG_rech.setObjectName("checkBox_HOG_rech")
        self.checkBox_Moments_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_Moments_rech.setGeometry(QtCore.QRect(290, 80, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Moments_rech.setFont(font)
        self.checkBox_Moments_rech.setObjectName("checkBox_Moments_rech")
        self.label_4 = QtWidgets.QLabel(self.tab_rech)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_requete = QtWidgets.QLabel(self.tab_rech)
        self.label_requete.setGeometry(QtCore.QRect(10, 180, 361, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_requete.setFont(font)
        self.label_requete.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_requete.setText("")
        self.label_requete.setScaledContents(True)
        self.label_requete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_requete.setObjectName("label_requete")
        self.progressBar_rech = QtWidgets.QProgressBar(self.tab_rech)
        self.progressBar_rech.setGeometry(QtCore.QRect(10, 440, 921, 41))
        self.progressBar_rech.setProperty("value", 0)
        self.progressBar_rech.setObjectName("progressBar_rech")
        self.label_5 = QtWidgets.QLabel(self.tab_rech)
        self.label_5.setGeometry(QtCore.QRect(380, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_rech)
        self.label_6.setGeometry(QtCore.QRect(940, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_rech)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(380, 180, 551, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 551, 251))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_courbe = QtWidgets.QLabel(self.tab_rech)
        self.label_courbe.setGeometry(QtCore.QRect(940, 180, 251, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_courbe.setFont(font)
        self.label_courbe.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_courbe.setText("")
        self.label_courbe.setScaledContents(True)
        self.label_courbe.setAlignment(QtCore.Qt.AlignCenter)
        self.label_courbe.setObjectName("label_courbe")
        self.quitter_rech = QtWidgets.QPushButton(self.tab_rech)
        self.quitter_rech.setGeometry(QtCore.QRect(940, 440, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quitter_rech.setFont(font)
        self.quitter_rech.setObjectName("quitter_rech")
        self.comboBox = QtWidgets.QComboBox(self.tab_rech)
        self.comboBox.setGeometry(QtCore.QRect(690, 70, 131, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.tab_rech)
        self.label_7.setGeometry(QtCore.QRect(590, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_rech)
        self.label_8.setGeometry(QtCore.QRect(380, 140, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_rech)
        self.label_9.setGeometry(QtCore.QRect(940, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.chercher = QtWidgets.QPushButton(self.tab_rech)
        self.chercher.setGeometry(QtCore.QRect(830, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chercher.setFont(font)
        self.chercher.setObjectName("chercher")
        self.calcul_RP = QtWidgets.QPushButton(self.tab_rech)
        self.calcul_RP.setGeometry(QtCore.QRect(940, 70, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calcul_RP.setFont(font)
        self.calcul_RP.setObjectName("calcul_RP")
        self.checkBox_autre_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_autre_rech.setGeometry(QtCore.QRect(290, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_autre_rech.setFont(font)
        self.checkBox_autre_rech.setObjectName("checkBox_autre_rech")
        self.charger_rech = QtWidgets.QPushButton(self.tab_rech)
        self.charger_rech.setGeometry(QtCore.QRect(10, 60, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_rech.setFont(font)
        self.charger_rech.setObjectName("charger_rech")
        self.label_10 = QtWidgets.QLabel(self.tab_rech)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.charger_desc = QtWidgets.QPushButton(self.tab_rech)
        self.charger_desc.setGeometry(QtCore.QRect(380, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_desc.setFont(font)
        self.charger_desc.setObjectName("charger_desc")
        self.tabWidget.addTab(self.tab_rech, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_SIFT_index.setText(_translate("MainWindow", "SIFT"))
        self.checkBox_ORB_index.setText(_translate("MainWindow", "ORB"))
        self.checkBox_HSV_index.setText(_translate("MainWindow", "Hist HSV"))
        self.checkBox_HistC_index.setText(_translate("MainWindow", "Hist Couleur"))
        self.checkBox_GLCM_index.setText(_translate("MainWindow", "GLCM"))
        self.checkBox_LBP_index.setText(_translate("MainWindow", "LBP"))
        self.checkBox_HOG_index.setText(_translate("MainWindow", "HOG"))
        self.charger.setText(_translate("MainWindow", "Charger et afficher la base de données"))
        self.quitter.setText(_translate("MainWindow", "Quitter"))
        self.indexer.setText(_translate("MainWindow", "Calculer les descripteurs"))
        self.label_3.setText(_translate("MainWindow", "Base d\'images"))
        self.label.setText(_translate("MainWindow", "Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_index), _translate("MainWindow", "Indexation"))
        self.label_2.setText(_translate("MainWindow", "Choix de descripteur"))
        self.checkBox_HistC_rech.setText(_translate("MainWindow", "BGR"))
        self.checkBox_HSV_rech.setText(_translate("MainWindow", "HSV"))
        self.checkBox_SIFT_rech.setText(_translate("MainWindow", "SIFT"))
        self.checkBox_ORB_rech.setText(_translate("MainWindow", "ORB"))
        self.checkBox_GLCM_rech.setText(_translate("MainWindow", "GLCM"))
        self.checkBox_LBP_rech.setText(_translate("MainWindow", "LBP"))
        self.checkBox_HOG_rech.setText(_translate("MainWindow", "HOG"))
        self.checkBox_Moments_rech.setText(_translate("MainWindow", "Mom."))
        self.label_4.setText(_translate("MainWindow", "Image requête"))
        self.label_5.setText(_translate("MainWindow", "Recherche"))
        self.label_6.setText(_translate("MainWindow", "Rappel/Précision"))
        self.quitter_rech.setText(_translate("MainWindow", "Quitter"))
        self.label_7.setText(_translate("MainWindow", "Distance :"))
        self.label_8.setText(_translate("MainWindow", "Résultats"))
        self.label_9.setText(_translate("MainWindow", "Courbe R/P"))
        self.chercher.setText(_translate("MainWindow", "Recherche"))
        self.calcul_RP.setText(_translate("MainWindow", "Calculer la courbe R/P"))
        self.checkBox_autre_rech.setText(_translate("MainWindow", "Autre"))
        self.charger_rech.setText(_translate("MainWindow", "Charger"))
        self.label_10.setText(_translate("MainWindow", "Requête"))
        self.charger_desc.setText(_translate("MainWindow", "Charger descripteurs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rech), _translate("MainWindow", "Recherche"))

        self.charger.clicked.connect(self.Ouvrir_index)

    def Ouvrir_index(self, MainWindow):
        self.list_images_index = []
        self.Dossier_images_index = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select directory', "C://", QtWidgets.QFileDialog.ShowDirsOnly)+"/"
        for i in range(len(os.listdir(self.Dossier_images_index))):
            self.filenames_index = self.Dossier_images_index + str(os.listdir(self.Dossier_images_index)[i])
            self.list_images_index.append(self.filenames_index)

        pixmap = QtGui.QPixmap(self.list_images_index[0])
        pixmap = pixmap.scaled(self.image.width(), self.image.height(), QtCore.Qt.KeepAspectRatio)
        self.image.setPixmap(pixmap)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        model = QtGui.QStandardItemModel()
        headerNames = []
        headerNames.append("File name")
        model.setHorizontalHeaderLabels(headerNames)
        #Afficher la liste d'images dans le tableView
        for i in range(len(self.list_images)):
            row = []
            first = self.list_images[i] #chemin complet
            second = os.path.basename(self.list_images[i]) #juste le nom du fichier
            item = QtGui.QStandardItem(first)
            item.setEditable(False)
            row.append(item)
            model.setColumnCount(1)
            model.appendRow(row)
        self.tableView.setModel(model)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
