# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_index = QtWidgets.QWidget()
        self.tab_index.setObjectName("tab_index")
        self.checkBox_SIFT_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_SIFT_index.setGeometry(QtCore.QRect(20, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_SIFT_index.setFont(font)
        self.checkBox_SIFT_index.setObjectName("checkBox_SIFT_index")
        self.checkBox_ORB_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_ORB_index.setGeometry(QtCore.QRect(150, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ORB_index.setFont(font)
        self.checkBox_ORB_index.setObjectName("checkBox_ORB_index")
        self.checkBox_HSV_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HSV_index.setGeometry(QtCore.QRect(480, 15, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HSV_index.setFont(font)
        self.checkBox_HSV_index.setObjectName("checkBox_HSV_index")
        self.checkBox_HistC_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HistC_index.setGeometry(QtCore.QRect(280, 15, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HistC_index.setFont(font)
        self.checkBox_HistC_index.setObjectName("checkBox_HistC_index")
        self.checkBox_GLCM_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_GLCM_index.setGeometry(QtCore.QRect(650, 15, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_GLCM_index.setFont(font)
        self.checkBox_GLCM_index.setObjectName("checkBox_GLCM_index")
        self.checkBox_LBP_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_LBP_index.setGeometry(QtCore.QRect(790, 15, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_LBP_index.setFont(font)
        self.checkBox_LBP_index.setObjectName("checkBox_LBP_index")
        self.checkBox_HOG_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_HOG_index.setGeometry(QtCore.QRect(910, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HOG_index.setFont(font)
        self.checkBox_HOG_index.setObjectName("checkBox_HOG_index")
        self.charger = QtWidgets.QPushButton(self.tab_index)
        self.charger.setGeometry(QtCore.QRect(10, 60, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger.setFont(font)
        self.charger.setObjectName("charger")
        self.quitter = QtWidgets.QPushButton(self.tab_index)
        self.quitter.setGeometry(QtCore.QRect(1070, 60, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quitter.setFont(font)
        self.quitter.setObjectName("quitter")
        self.indexer = QtWidgets.QPushButton(self.tab_index)
        self.indexer.setGeometry(QtCore.QRect(600, 60, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.indexer.setFont(font)
        self.indexer.setObjectName("indexer")
        self.imagelabel = QtWidgets.QLabel(self.tab_index)
        self.imagelabel.setGeometry(QtCore.QRect(10, 110, 261, 231))
        self.imagelabel.setAutoFillBackground(False)
        self.imagelabel.setText("")
        self.imagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imagelabel.setObjectName("imagelabel")
        self.image = QtWidgets.QLabel(self.tab_index)
        self.image.setGeometry(QtCore.QRect(10, 160, 581, 331))
        self.image.setFrameShape(QtWidgets.QFrame.Panel)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.label_3 = QtWidgets.QLabel(self.tab_index)
        self.label_3.setGeometry(QtCore.QRect(600, 120, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab_index)
        self.label.setGeometry(QtCore.QRect(10, 120, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.tab_index)
        self.progressBar.setGeometry(QtCore.QRect(10, 500, 1181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tableView = QtWidgets.QTableView(self.tab_index)
        self.tableView.setGeometry(QtCore.QRect(600, 160, 591, 331))
        self.tableView.setObjectName("tableView")
        self.checkBox_MobileNet_index = QtWidgets.QCheckBox(self.tab_index)
        self.checkBox_MobileNet_index.setGeometry(QtCore.QRect(1040, 15, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_MobileNet_index.setFont(font)
        self.checkBox_MobileNet_index.setObjectName("checkBox_MobileNet_index")
        self.tabWidget.addTab(self.tab_index, "")
        self.tab_rech = QtWidgets.QWidget()
        self.tab_rech.setObjectName("tab_rech")
        self.label_2 = QtWidgets.QLabel(self.tab_rech)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.checkBox_HistC_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HistC_rech.setGeometry(QtCore.QRect(100, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.checkBox_HistC_rech.setFont(font)
        self.checkBox_HistC_rech.setObjectName("checkBox_HistC_rech")
        self.checkBox_HSV_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HSV_rech.setGeometry(QtCore.QRect(170, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HSV_rech.setFont(font)
        self.checkBox_HSV_rech.setObjectName("checkBox_HSV_rech")
        self.checkBox_SIFT_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_SIFT_rech.setGeometry(QtCore.QRect(100, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_SIFT_rech.setFont(font)
        self.checkBox_SIFT_rech.setObjectName("checkBox_SIFT_rech")
        self.checkBox_ORB_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_ORB_rech.setGeometry(QtCore.QRect(170, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ORB_rech.setFont(font)
        self.checkBox_ORB_rech.setObjectName("checkBox_ORB_rech")
        self.checkBox_GLCM_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_GLCM_rech.setGeometry(QtCore.QRect(250, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_GLCM_rech.setFont(font)
        self.checkBox_GLCM_rech.setObjectName("checkBox_GLCM_rech")
        self.checkBox_LBP_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_LBP_rech.setGeometry(QtCore.QRect(100, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_LBP_rech.setFont(font)
        self.checkBox_LBP_rech.setObjectName("checkBox_LBP_rech")
        self.checkBox_HOG_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_HOG_rech.setGeometry(QtCore.QRect(250, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_HOG_rech.setFont(font)
        self.checkBox_HOG_rech.setObjectName("checkBox_HOG_rech")
        self.label_4 = QtWidgets.QLabel(self.tab_rech)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_requete = QtWidgets.QLabel(self.tab_rech)
        self.label_requete.setGeometry(QtCore.QRect(10, 190, 311, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_requete.setFont(font)
        self.label_requete.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_requete.setText("")
        self.label_requete.setScaledContents(True)
        self.label_requete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_requete.setObjectName("label_requete")
        self.progressBar_rech = QtWidgets.QProgressBar(self.tab_rech)
        self.progressBar_rech.setGeometry(QtCore.QRect(10, 490, 921, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_rech.setFont(font)
        self.progressBar_rech.setProperty("value", 0)
        self.progressBar_rech.setObjectName("progressBar_rech")
        self.label_5 = QtWidgets.QLabel(self.tab_rech)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_rech)
        self.label_6.setGeometry(QtCore.QRect(820, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.quitter_rech = QtWidgets.QPushButton(self.tab_rech)
        self.quitter_rech.setGeometry(QtCore.QRect(940, 490, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quitter_rech.setFont(font)
        self.quitter_rech.setObjectName("quitter_rech")
        self.comboBox = QtWidgets.QComboBox(self.tab_rech)
        self.comboBox.setGeometry(QtCore.QRect(460, 100, 221, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.tab_rech)
        self.label_7.setGeometry(QtCore.QRect(330, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_rech)
        self.label_8.setGeometry(QtCore.QRect(330, 150, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_rech)
        self.label_9.setGeometry(QtCore.QRect(820, 270, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.chercher = QtWidgets.QPushButton(self.tab_rech)
        self.chercher.setGeometry(QtCore.QRect(690, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chercher.setFont(font)
        self.chercher.setObjectName("chercher")
        self.calcul_RP = QtWidgets.QPushButton(self.tab_rech)
        self.calcul_RP.setGeometry(QtCore.QRect(1000, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calcul_RP.setFont(font)
        self.calcul_RP.setObjectName("calcul_RP")
        self.charger_rech = QtWidgets.QPushButton(self.tab_rech)
        self.charger_rech.setGeometry(QtCore.QRect(10, 60, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_rech.setFont(font)
        self.charger_rech.setObjectName("charger_rech")
        self.label_10 = QtWidgets.QLabel(self.tab_rech)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.charger_desc = QtWidgets.QPushButton(self.tab_rech)
        self.charger_desc.setGeometry(QtCore.QRect(330, 50, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_desc.setFont(font)
        self.charger_desc.setObjectName("charger_desc")
        self.label_courbe = QtWidgets.QLabel(self.tab_rech)
        self.label_courbe.setGeometry(QtCore.QRect(820, 310, 371, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_courbe.setFont(font)
        self.label_courbe.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_courbe.setText("")
        self.label_courbe.setScaledContents(True)
        self.label_courbe.setAlignment(QtCore.Qt.AlignCenter)
        self.label_courbe.setObjectName("label_courbe")
        self.pushButton = QtWidgets.QPushButton(self.tab_rech)
        self.pushButton.setGeometry(QtCore.QRect(820, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_11 = QtWidgets.QLabel(self.tab_rech)
        self.label_11.setGeometry(QtCore.QRect(820, 100, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_metriques = QtWidgets.QLabel(self.tab_rech)
        self.label_metriques.setGeometry(QtCore.QRect(820, 140, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_metriques.setFont(font)
        self.label_metriques.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_metriques.setText("")
        self.label_metriques.setScaledContents(True)
        self.label_metriques.setAlignment(QtCore.Qt.AlignCenter)
        self.label_metriques.setObjectName("label_metriques")
        self.label_12 = QtWidgets.QLabel(self.tab_rech)
        self.label_12.setGeometry(QtCore.QRect(540, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_top = QtWidgets.QComboBox(self.tab_rech)
        self.comboBox_top.setGeometry(QtCore.QRect(630, 50, 181, 41))
        self.comboBox_top.setObjectName("comboBox_top")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_rech)
        self.scrollArea.setGeometry(QtCore.QRect(330, 190, 481, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        # self.gridLayoutWidget.setEnabled(True)
        # self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 271))
        # self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        # self.gridLayoutWidget_2 = QtWidgets.QWidget(self.gridLayoutWidget)
        # self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 461, 271))
        # self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        # self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        # self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        # self.gridLayout.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout.setSpacing(0)
        # self.gridLayout.setObjectName("gridLayout")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        # Contenu scrollable
        self.scrollContent = QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scrollContent)

        # Layout du contenu (grille d’images)
        self.gridLayout = QtWidgets.QGridLayout(self.scrollContent)
        self.checkBox_MobileNet_rech = QtWidgets.QCheckBox(self.tab_rech)
        self.checkBox_MobileNet_rech.setGeometry(QtCore.QRect(170, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_MobileNet_rech.setFont(font)
        self.checkBox_MobileNet_rech.setObjectName("checkBox_MobileNet_rech")
        self.tabWidget.addTab(self.tab_rech, "")
        self.tab_multimodal = QtWidgets.QWidget()
        self.tab_multimodal.setObjectName("tab_multimodal")
        self.charger_image_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.charger_image_mult.setGeometry(QtCore.QRect(20, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_image_mult.setFont(font)
        self.charger_image_mult.setObjectName("charger_image_mult")
        self.text_request = QtWidgets.QTextEdit(self.tab_multimodal)
        self.text_request.setGeometry(QtCore.QRect(20, 50, 291, 51))
        self.text_request.setObjectName("text_request")
        self.label_texte_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_texte_mult.setGeometry(QtCore.QRect(10, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_texte_mult.setFont(font)
        self.label_texte_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_texte_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_texte_mult.setObjectName("label_texte_mult")
        self.label_img_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_img_mult.setGeometry(QtCore.QRect(10, 110, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_img_mult.setFont(font)
        self.label_img_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_img_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_mult.setObjectName("label_img_mult")
        self.label_rech_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_rech_mult.setGeometry(QtCore.QRect(330, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_rech_mult.setFont(font)
        self.label_rech_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_rech_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rech_mult.setObjectName("label_rech_mult")
        self.label_RP_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_RP_mult.setGeometry(QtCore.QRect(820, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_RP_mult.setFont(font)
        self.label_RP_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_RP_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RP_mult.setObjectName("label_RP_mult")
        self.label_requete_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_requete_mult.setGeometry(QtCore.QRect(10, 210, 311, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_requete_mult.setFont(font)
        self.label_requete_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_requete_mult.setText("")
        self.label_requete_mult.setScaledContents(True)
        self.label_requete_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_requete_mult.setObjectName("label_requete_mult")
        self.charger_desc_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.charger_desc_mult.setGeometry(QtCore.QRect(330, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.charger_desc_mult.setFont(font)
        self.charger_desc_mult.setStyleSheet("background-color: rgb(214, 0, 0);")
        self.charger_desc_mult.setObjectName("charger_desc_mult")
        self.comboBox_top_mult = QtWidgets.QComboBox(self.tab_multimodal)
        self.comboBox_top_mult.setGeometry(QtCore.QRect(630, 60, 181, 41))
        self.comboBox_top_mult.setObjectName("comboBox_top_mult")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.comboBox_top_mult.addItem("")
        self.label_top_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_top_mult.setGeometry(QtCore.QRect(540, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_top_mult.setFont(font)
        self.label_top_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_top_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top_mult.setObjectName("label_top_mult")
        self.chercher_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.chercher_mult.setGeometry(QtCore.QRect(430, 110, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chercher_mult.setFont(font)
        self.chercher_mult.setObjectName("chercher_mult")
        self.label_results_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_results_mult.setGeometry(QtCore.QRect(330, 160, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_results_mult.setFont(font)
        self.label_results_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_results_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_results_mult.setObjectName("label_results_mult")
        self.scrollArea_mult = QtWidgets.QScrollArea(self.tab_multimodal)
        self.scrollArea_mult.setGeometry(QtCore.QRect(330, 210, 481, 291))
        self.scrollArea_mult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_mult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_mult.setWidgetResizable(True)
        self.scrollArea_mult.setObjectName("scrollArea_mult")
        self.scrollArea_content_mult = QtWidgets.QWidget()
        self.scrollArea_content_mult.setGeometry(QtCore.QRect(0, 0, 479, 289))
        self.scrollArea_content_mult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_content_mult.setObjectName("scrollArea_content_mult")
        self.scrollArea_mult.setWidget(self.scrollArea_content_mult)
        self.progressBar_mult = QtWidgets.QProgressBar(self.tab_multimodal)
        self.progressBar_mult.setGeometry(QtCore.QRect(10, 510, 801, 21))
        self.progressBar_mult.setProperty("value", 0)
        self.progressBar_mult.setObjectName("progressBar_mult")
        self.quitter_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.quitter_mult.setGeometry(QtCore.QRect(830, 460, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quitter_mult.setFont(font)
        self.quitter_mult.setObjectName("quitter_mult")
        self.clear_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.clear_mult.setGeometry(QtCore.QRect(830, 400, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clear_mult.setFont(font)
        self.clear_mult.setObjectName("clear_mult")
        self.retirer_image_mult = QtWidgets.QPushButton(self.tab_multimodal)
        self.retirer_image_mult.setGeometry(QtCore.QRect(180, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.retirer_image_mult.setFont(font)
        self.retirer_image_mult.setObjectName("retirer_image_mult")
        self.label_metriques_mult = QtWidgets.QLabel(self.tab_multimodal)
        self.label_metriques_mult.setGeometry(QtCore.QRect(820, 60, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_metriques_mult.setFont(font)
        self.label_metriques_mult.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_metriques_mult.setText("")
        self.label_metriques_mult.setScaledContents(True)
        self.label_metriques_mult.setAlignment(QtCore.Qt.AlignCenter)
        self.label_metriques_mult.setObjectName("label_metriques_mult")
        self.tabWidget.addTab(self.tab_multimodal, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_SIFT_index.setText(_translate("MainWindow", "SIFT"))
        self.checkBox_ORB_index.setText(_translate("MainWindow", "ORB"))
        self.checkBox_HSV_index.setText(_translate("MainWindow", "Hist HSV"))
        self.checkBox_HistC_index.setText(_translate("MainWindow", "Hist Couleur"))
        self.checkBox_GLCM_index.setText(_translate("MainWindow", "GLCM"))
        self.checkBox_LBP_index.setText(_translate("MainWindow", "LBP"))
        self.checkBox_HOG_index.setText(_translate("MainWindow", "HOG"))
        self.charger.setText(_translate("MainWindow", "Charger et afficher la base de données"))
        self.quitter.setText(_translate("MainWindow", "Quitter"))
        self.indexer.setText(_translate("MainWindow", "Calculer les descripteurs"))
        self.label_3.setText(_translate("MainWindow", "Base d\'images"))
        self.label.setText(_translate("MainWindow", "Image"))
        self.checkBox_MobileNet_index.setText(_translate("MainWindow", "MobileNet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_index), _translate("MainWindow", "Indexation"))
        self.label_2.setText(_translate("MainWindow", "Choix de descripteur"))
        self.checkBox_HistC_rech.setText(_translate("MainWindow", "BGR"))
        self.checkBox_HSV_rech.setText(_translate("MainWindow", "HSV"))
        self.checkBox_SIFT_rech.setText(_translate("MainWindow", "SIFT"))
        self.checkBox_ORB_rech.setText(_translate("MainWindow", "ORB"))
        self.checkBox_GLCM_rech.setText(_translate("MainWindow", "GLCM"))
        self.checkBox_LBP_rech.setText(_translate("MainWindow", "LBP"))
        self.checkBox_HOG_rech.setText(_translate("MainWindow", "HOG"))
        self.label_4.setText(_translate("MainWindow", "Image requête"))
        self.label_5.setText(_translate("MainWindow", "Recherche"))
        self.label_6.setText(_translate("MainWindow", "Rappel/Précision"))
        self.quitter_rech.setText(_translate("MainWindow", "Quitter"))
        self.label_7.setText(_translate("MainWindow", "Distance :"))
        self.label_8.setText(_translate("MainWindow", "Résultats"))
        self.label_9.setText(_translate("MainWindow", "Courbe R/P"))
        self.chercher.setText(_translate("MainWindow", "Recherche"))
        self.calcul_RP.setText(_translate("MainWindow", "Calculer la courbe R/P"))
        self.charger_rech.setText(_translate("MainWindow", "Charger"))
        self.label_10.setText(_translate("MainWindow", "Requête"))
        self.charger_desc.setText(_translate("MainWindow", "Charger descripteurs"))
        self.pushButton.setText(_translate("MainWindow", "Calculer métriques"))
        self.label_11.setText(_translate("MainWindow", "Métriques"))
        self.label_12.setText(_translate("MainWindow", "Top :"))
        self.checkBox_MobileNet_rech.setText(_translate("MainWindow", "MobileNet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rech), _translate("MainWindow", "Recherche"))
        self.charger_image_mult.setText(_translate("MainWindow", "Charger "))
        self.text_request.setDocumentTitle(_translate("MainWindow", "ttttt"))
        self.label_texte_mult.setText(_translate("MainWindow", "Texte  (anglais uniquement)"))
        self.label_img_mult.setText(_translate("MainWindow", "Image requête"))
        self.label_rech_mult.setText(_translate("MainWindow", "Recherche"))
        self.label_RP_mult.setText(_translate("MainWindow", "Rappel/Précision"))
        self.charger_desc_mult.setText(_translate("MainWindow", "Charger descripteurs"))
        self.comboBox_top_mult.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_top_mult.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_top_mult.setItemText(2, _translate("MainWindow", "15"))
        self.comboBox_top_mult.setItemText(3, _translate("MainWindow", "20"))
        self.comboBox_top_mult.setItemText(4, _translate("MainWindow", "50"))
        self.comboBox_top_mult.setItemText(5, _translate("MainWindow", "100"))
        self.comboBox_top_mult.setItemText(6, _translate("MainWindow", "150"))
        self.comboBox_top_mult.setItemText(7, _translate("MainWindow", "153"))
        self.label_top_mult.setText(_translate("MainWindow", "Top :"))
        self.chercher_mult.setText(_translate("MainWindow", "Recherche"))
        self.label_results_mult.setText(_translate("MainWindow", "Résultats"))
        self.quitter_mult.setText(_translate("MainWindow", "Quitter"))
        self.clear_mult.setText(_translate("MainWindow", "Clear"))
        self.retirer_image_mult.setText(_translate("MainWindow", "Retirer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_multimodal), _translate("MainWindow", "Multimodale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
